// <auto-generated/>
namespace $rootnamespace$.Logging.LogProviders
{
    using System;

	/// <summary>
    /// Exception thrown by LibLog.
    /// </summary>
    public class LibLogException : Exception
    {
		/// <summary>
        /// Initializes a new LibLogException with the specified message.
        /// </summary>
        /// <param name="message">The message</param>
        public LibLogException(string message)
            : base(message)
        {
        }

		/// <summary>
        /// Initializes a new LibLogException with the specified message and inner exception.
        /// </summary>
        /// <param name="message">The message.</param>
        /// <param name="inner">The inner exception.</param>
        public LibLogException(string message, Exception inner)
            : base(message, inner)
        {
        }
    }
}
