// <auto-generated/>
// ReSharper disable CheckNamespace
namespace $rootnamespace$.Logging
{
    /// <summary>
    ///     The log level.
    /// </summary>
#if LIBLOG_PROVIDERS_ONLY
    internal
#else
    public
#endif
        enum LogLevel
    {
        /// <summary>
        /// Trace
        /// </summary>
        Trace,

        /// <summary>
        /// Debug
        /// </summary>
        Debug,

        /// <summary>
        /// Info
        /// </summary>
        Info,

        /// <summary>
        /// Warn
        /// </summary>
        Warn,

        /// <summary>
        /// Error
        /// </summary>
        Error,

        /// <summary>
        /// Fatal
        /// </summary>
        Fatal
    }
}
